title: "Teaching Tech Together"
author: "Greg Wilson"
purchase: "http://www.lulu.com/commerce/index.php?fBuyContent=23123539"
lulu: "http://www.lulu.com/shop/greg-wilson/teaching-tech-together/paperback/product-23715287.html"
repository: "https://github.com/gvwilson/teachtogether.tech"
